# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/argo-10/Desktop/i2c_project_updated/i2c_project_updated.cache/wt [current_project]
set_property parent.project_path C:/Users/argo-10/Desktop/i2c_project_updated/i2c_project_updated.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo c:/Users/argo-10/Desktop/i2c_project_updated/i2c_project_updated.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/argo-10/Desktop/i2c_master_new.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top i2c_master_new -part xc7z020clg484-1


write_checkpoint -force -noxdef i2c_master_new.dcp

catch { report_utilization -file i2c_master_new_utilization_synth.rpt -pb i2c_master_new_utilization_synth.pb }
